package test.web;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class MinhasAtividades2Test {
    private WebDriver driver;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();

        js = (JavascriptExecutor) driver;
        Map<String, Object> vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
       /* if (driver != null) {
            driver.quit();
        }*/
    }
    @Test
    public void minhasAtividades2() {
        driver.get("https://testando.eveclass.com/pt/admin/conteudo");
        driver.manage().window().setSize(new Dimension(1024, 728));
        //WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
        //WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".dropdown:nth-child(2) > .dropdown-icon")));
        driver.findElement(By.cssSelector(".dropdown:nth-child(2) > .dropdown-icon")).click();
        driver.findElement(By.cssSelector(".dropdown-item:nth-child(3) .infos-text")).click();
        driver.findElement(By.cssSelector(".button-text > span")).click();
        js.executeScript("window.scrollTo(0,0)");
        {
            WebElement element = driver.findElement(By.cssSelector(".button-text > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
    }
}